
POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer toekn

{
  "title": "No Time to Die",
  "author": "Billie Eilish",
  "url": "http://www.testing.com",
  "likes": 20,
  "userId": "6291cc776df80670c5876e7e"
}
